(function($){Drupal.ajax.prototype.commands.viewsLoadMoreAppend=function(ajax,response,status){var wrapper=response.selector?$(response.selector):$(ajax.wrapper);var method=response.method||ajax.method;var targetList=response.targetList||'';var effect=ajax.getEffect(response);var pager_selector=response.options.pager_selector?response.options.pager_selector:'.pager-load-more';var new_content_wrapped=$('<div></div>').html(response.data);var new_content=new_content_wrapped.contents();if(new_content.length!=1||new_content.get(0).nodeType!=1){new_content=new_content_wrapped;}
var settings=response.settings||ajax.settings||Drupal.settings;Drupal.detachBehaviors(wrapper,settings);if($.waypoints!=undefined){$.waypoints('refresh');}
var content_query=targetList&&!response.options.content?'> .view-content '+targetList:response.options.content||'> .view-content';if(effect.showEffect!='show'){new_content.find(content_query).children().hide();}
wrapper.find(pager_selector).replaceWith(new_content.find(pager_selector));wrapper.find(content_query)[method](new_content.find(content_query).children());wrapper.find(content_query).children().removeClass('views-row-first views-row-last views-row-odd views-row-even').filter(':first').addClass('views-row-first').end().filter(':last').addClass('views-row-last').end().filter(':even').addClass('views-row-odd').end().filter(':odd').addClass('views-row-even').end();if(effect.showEffect!='show'){wrapper.find(content_query).children(':not(:visible)')[effect.showEffect](effect.showSpeed);}
wrapper.trigger('views_load_more.new_content',new_content.clone());var classes=wrapper.attr('class');var onceClass=classes.match(/jquery-once-[0-9]*-[a-z]*/);wrapper.removeClass(onceClass[0]);settings=response.settings||ajax.settings||Drupal.settings;Drupal.attachBehaviors(wrapper,settings);};Drupal.behaviors.ViewsLoadMore={attach:function(context,settings){var default_opts={offset:'100%'};if(settings&&settings.viewsLoadMore&&settings.views&&settings.views.ajaxViews){$.each(settings.viewsLoadMore,function(i,setting){var view='.view-id-'+setting.view_name+'.view-display-id-'+setting.view_display_id+' .pager-next a',opts={};$.extend(opts,default_opts,settings.viewsLoadMore[i].opts);$(view).waypoint('destroy');$(view).waypoint(function(event,direction){$(view).click();},opts);});}},detach:function(context,settings,trigger){if(settings&&settings.viewsLoadMore&&settings.views&&settings.views.ajaxViews){$.each(settings.viewsLoadMore,function(i,setting){var view='.view-id-'+setting.view_name+'.view-display-id-'+setting.view_display_id;if($(context).is(view)){$('.pager-next a',view).waypoint('destroy');}
else{$(view,context).waypoint('destroy');}});}}};})(jQuery);;(function($){Drupal.Views={};Drupal.behaviors.viewsTabs={attach:function(context){if($.viewsUi&&$.viewsUi.tabs){$('#views-tabset').once('views-processed').viewsTabs({selectedClass:'active'});}
$('a.views-remove-link').once('views-processed').click(function(event){var id=$(this).attr('id').replace('views-remove-link-','');$('#views-row-'+id).hide();$('#views-removed-'+id).attr('checked',true);event.preventDefault();});$('a.display-remove-link').addClass('display-processed').click(function(){var id=$(this).attr('id').replace('display-remove-link-','');$('#display-row-'+id).hide();$('#display-removed-'+id).attr('checked',true);return false;});}};Drupal.Views.parseQueryString=function(query){var args={};var pos=query.indexOf('?');if(pos!=-1){query=query.substring(pos+1);}
var pairs=query.split('&');for(var i in pairs){if(typeof(pairs[i])=='string'){var pair=pairs[i].split('=');if(pair[0]!='q'&&pair[1]){args[decodeURIComponent(pair[0].replace(/\+/g,' '))]=decodeURIComponent(pair[1].replace(/\+/g,' '));}}}
return args;};Drupal.Views.parseViewArgs=function(href,viewPath){if(Drupal.settings.pathPrefix){var viewPath=Drupal.settings.pathPrefix+viewPath;}
var returnObj={};var path=Drupal.Views.getPath(href);if(viewPath&&path.substring(0,viewPath.length+1)==viewPath+'/'){var args=decodeURIComponent(path.substring(viewPath.length+1,path.length));returnObj.view_args=args;returnObj.view_path=path;}
return returnObj;};Drupal.Views.pathPortion=function(href){var protocol=window.location.protocol;if(href.substring(0,protocol.length)==protocol){href=href.substring(href.indexOf('/',protocol.length+2));}
return href;};Drupal.Views.getPath=function(href){href=Drupal.Views.pathPortion(href);href=href.substring(Drupal.settings.basePath.length,href.length);if(href.substring(0,3)=='?q='){href=href.substring(3,href.length);}
var chars=['#','?','&'];for(var i in chars){if(href.indexOf(chars[i])>-1){href=href.substr(0,href.indexOf(chars[i]));}}
return href;};})(jQuery);;(function($){Drupal.progressBar=function(id,updateCallback,method,errorCallback){var pb=this;this.id=id;this.method=method||'GET';this.updateCallback=updateCallback;this.errorCallback=errorCallback;this.element=$('<div class="progress" aria-live="polite"></div>').attr('id',id);this.element.html('<div class="bar"><div class="filled"></div></div>'+
'<div class="percentage"></div>'+
'<div class="message">&nbsp;</div>');};Drupal.progressBar.prototype.setProgress=function(percentage,message){if(percentage>=0&&percentage<=100){$('div.filled',this.element).css('width',percentage+'%');$('div.percentage',this.element).html(percentage+'%');}
$('div.message',this.element).html(message);if(this.updateCallback){this.updateCallback(percentage,message,this);}};Drupal.progressBar.prototype.startMonitoring=function(uri,delay){this.delay=delay;this.uri=uri;this.sendPing();};Drupal.progressBar.prototype.stopMonitoring=function(){clearTimeout(this.timer);this.uri=null;};Drupal.progressBar.prototype.sendPing=function(){if(this.timer){clearTimeout(this.timer);}
if(this.uri){var pb=this;$.ajax({type:this.method,url:this.uri,data:'',dataType:'json',success:function(progress){if(progress.status==0){pb.displayError(progress.data);return;}
pb.setProgress(progress.percentage,progress.message);pb.timer=setTimeout(function(){pb.sendPing();},pb.delay);},error:function(xmlhttp){pb.displayError(Drupal.ajaxError(xmlhttp,pb.uri));}});}};Drupal.progressBar.prototype.displayError=function(string){var error=$('<div class="messages error"></div>').html(string);$(this.element).before(error).hide();if(this.errorCallback){this.errorCallback(this);}};})(jQuery);;(function($){Drupal.behaviors.ViewsAjaxView={};Drupal.behaviors.ViewsAjaxView.attach=function(){if(Drupal.settings&&Drupal.settings.views&&Drupal.settings.views.ajaxViews){$.each(Drupal.settings.views.ajaxViews,function(i,settings){Drupal.views.instances[i]=new Drupal.views.ajaxView(settings);});}};Drupal.views={};Drupal.views.instances={};Drupal.views.ajaxView=function(settings){var selector='.view-dom-id-'+settings.view_dom_id;this.$view=$(selector);var ajax_path=Drupal.settings.views.ajax_path;if(ajax_path.constructor.toString().indexOf("Array")!=-1){ajax_path=ajax_path[0];}
var queryString=window.location.search||'';if(queryString!==''){var queryString=queryString.slice(1).replace(/q=[^&]+&?|&?render=[^&]+/,'');if(queryString!==''){queryString=((/\?/.test(ajax_path))?'&':'?')+queryString;}}
this.element_settings={url:ajax_path+queryString,submit:settings,setClick:true,event:'click',selector:selector,progress:{type:'throbber'}};this.settings=settings;this.$exposed_form=$('#views-exposed-form-'+settings.view_name.replace(/_/g,'-')+'-'+settings.view_display_id.replace(/_/g,'-'));this.$exposed_form.once(jQuery.proxy(this.attachExposedFormAjax,this));this.links=[];this.$view.once(jQuery.proxy(this.attachPagerAjax,this));var self_settings=this.element_settings;self_settings.event='RefreshView';var self=this;this.$view.once('refresh',function(){self.refreshViewAjax=new Drupal.ajax(self.selector,self.$view,self_settings);});};Drupal.views.ajaxView.prototype.attachExposedFormAjax=function(){var button=$('input[type=submit], button[type=submit], input[type=image]',this.$exposed_form);button=button[0];$(button).click(function(){if(Drupal.autocompleteSubmit){Drupal.autocompleteSubmit();}});this.exposedFormAjax=new Drupal.ajax($(button).attr('id'),button,this.element_settings);};Drupal.views.ajaxView.prototype.attachPagerAjax=function(){this.$view.find('ul.pager > li > a, ol.pager > li > a, th.views-field a, .attachment .views-summary a').each(jQuery.proxy(this.attachPagerLinkAjax,this));};Drupal.views.ajaxView.prototype.attachPagerLinkAjax=function(id,link){var $link=$(link);var viewData={};var href=$link.attr('href');if($link.closest('.view')[0]!==this.$view[0]&&$link.closest('.view').parent().hasClass('attachment')===false){return;}
if(typeof(viewData.page)==='undefined'){viewData.page=0;}
$.extend(viewData,this.settings,Drupal.Views.parseQueryString(href),Drupal.Views.parseViewArgs(href,this.settings.view_base_path));$.extend(viewData,Drupal.Views.parseViewArgs(href,this.settings.view_base_path));this.element_settings.submit=viewData;this.pagerAjax=new Drupal.ajax(false,$link,this.element_settings);this.links.push(this.pagerAjax);};Drupal.ajax.prototype.commands.viewsScrollTop=function(ajax,response,status){var offset=$(response.selector).offset();var scrollTarget=response.selector;while($(scrollTarget).scrollTop()==0&&$(scrollTarget).parent()){scrollTarget=$(scrollTarget).parent();}
if(offset.top-10<$(scrollTarget).scrollTop()){$(scrollTarget).animate({scrollTop:(offset.top-10)},500);}};})(jQuery);;